name: CI

on: [push, pull_request]

jobs:
  test-all:
    name: UnitTests on ST${{ matrix.st-version }} ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        arch:
          - x86
          - x64
        st-version:
          - 3
          - 4
        exclude:
          - st-version: 4
            arch: x86
          - os: macos-latest
            arch: x86
          - os: ubuntu-latest
            arch: x86
    steps:
      - uses: actions/checkout@v4
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          package-name: Package Control
          sublime-text-version: ${{ matrix.st-version }}
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
        with:
          package-name: Package Control
        env:
          GH_PASS: ${{ secrets.GH_PASS }}
          GL_PASS: ${{ secrets.GL_PASS }}
          BB_PASS: ${{ secrets.BB_PASS }}

  lint:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -U flake8
      - name: Run linter
        run: flake8
